# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyforward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='email',
            field=models.CharField(default='rhymis@acf.hhs.gov', max_length=100),
        ),
    ]
